### ISSUE TITLE
Un-Readable Text in Dim Mode

### ISSUE THREAD

**Issue by cod3r12** [canvasplus/extension#23]
I've noticed that when I'm using dim mode (and this might go for dark mode too) that the main text is very hard to read because it blends into the background.

**Comment by adrWasTaken** [comment]
Hi, thanks for reaching out about this! 👋

I’m not really sure what you mean by “Main Text”. Could you clarify and/or send a screenshot?

Thanks!

**Comment by cod3r12** [comment]
Sorry about being in-specific. Hopefully this screenshot will help. As you can see, this text blends in and is hard to read. This goes for most text.
https://user-images.githubusercontent.com/85259706/132606306-d3f62cbe-d57d-4059-9eae-0f86437cc240.png
(I hope this image works for you)

**Comment by J-Coding-Dev** [comment]
That should be sufficient.

**Comment by adrWasTaken** [comment]
Hi, we're having a hard time recreating this issue on a similar page layout. Could you please supply us with your Chrome or Firefox version (chrome://settings/help) while we work on this?

**Comment by cod3r12** [comment]
I'm on chrome v93

**Comment by adrWasTaken** [comment]
Unfortunately, we're not able to identify the issue you're having, but we'll be working soon to prevent this from happening based on some likely causes. Thanks.
