### ISSUE TITLE
Suggestion: Disable search for locked pages

### ISSUE THREAD

**Issue by kittyconfusion** [canvasplus/extension#24]
I know that search categorizes all pages and assignments in modules. However, some pages still exist that show up in search and in the list of all pages that are unavailable for viewing. Would it be possible to stop these from showing up in search even though the pages still technically exist?

Example:
![image](https://user-images.githubusercontent.com/65476906/133838579-04628ec1-85fa-47a4-ac91-d6b280fa72a7.png)

Thank you!

**Comment by adrWasTaken** [comment]
Hi, we're currently working on an overhaul of search, but we'll make sure to include this, perhaps by putting disabled results below enabled results, and putting lock icon next to them.
