### ISSUE TITLE
Dark mode text color

### ISSUE THREAD

**Issue by TyHil** [canvasplus/extension#28]
Almost all of the text in dark mode has the color #2d3b45 which has low contrast with the background and is difficult to read. I think this style is applied and inherited from the body selector in Canvas' native CSS. The dark mode is not usable with this low contrast and it would be great if Canvas+ could change the text color along with the background and other aspects.
![image](https://user-images.githubusercontent.com/63886162/137188488-00992d91-2949-47d7-a586-79b8a1cb5a5f.png)

**Comment by adrWasTaken** [comment]
Hi, are you still having this issue? If so, please try reinstalling and/or fidgeting with your display settings and seeing if that fixes it. Thanks!

**Comment by adrWasTaken** [comment]
Would you mind sending a screenshot of your chrome devtools?

**Comment by TyHil** [comment]
Sure.
[image: image.png]

**Comment by adrWasTaken** [comment]
@Shilab66 your issue has been fixed. Please make a separate issue next time as the issues are separate.
@TyHil we're looking into your issue. It will be fixed soon. 😄

**Comment by adrWasTaken** [comment]
Hi, please let me know if running this code in the console fixes the issue @TyHil 
`document.body.setAttribute('style','color:var(--ic-brand-font-color-dark) !important;')`

**Comment by Jelly2011** [comment]
> Hi, please let me know if running this code in the console fixes the issue @TyHil `document.body.setAttribute('style','color:var(--ic-brand-font-color-dark) !important;')`

Running this script did fix text contrast issues for me when opening an assignment but text in modules that link to assignments still does not have great contrast.

**Comment by TyHil** [comment]
Same here. That seems to fix normal text but not link text.

**Comment by adrWasTaken** [comment]
Does link text change if you adjust your link color in settings?

**Comment by Jelly2011** [comment]
No only links that go to websites

**Comment by adrWasTaken** [comment]
So these links don't change color is what you're saying?
<img width="165" alt="image" src="https://user-images.githubusercontent.com/67245238/141594229-8ea85001-39b2-4e62-8733-43c2af179453.png">
Let me know if it looks like the screenshot below vv
<img width="167" alt="image" src="https://user-images.githubusercontent.com/67245238/141594268-a3473599-6322-4495-aaf9-07f0a529a0fc.png">

**Comment by Jelly2011** [comment]
> So these links don't change color is what you're saying? <img alt="image" width="165" src="https://user-images.githubusercontent.com/67245238/141594229-8ea85001-39b2-4e62-8733-43c2af179453.png"> Let me know if it looks like the screenshot below vv <img alt="image" width="167" src="https://user-images.githubusercontent.com/67245238/141594268-a3473599-6322-4495-aaf9-07f0a529a0fc.png">

The links in this section do change color but the links in these sections don't adjust
![image](https://user-images.githubusercontent.com/59700364/141596698-86fd868b-6868-46cf-9a6b-12fc8cb4b7a4.png)
![image](https://user-images.githubusercontent.com/59700364/141596732-af9d73f6-03d0-4dc2-9757-1596ab509dc6.png)

**Comment by adrWasTaken** [comment]
Got it. Are either of y'all using high contrast mode? @TyHil

**Comment by Jelly2011** [comment]
I'm using high contrast mode in carmen. Turning off high contrast makes fixes text in this area 
![image](https://user-images.githubusercontent.com/59700364/141597020-c4bec0d4-7a09-4e3b-93cc-923bba49cf6a.png)
but not in this area
![image](https://user-images.githubusercontent.com/59700364/141597068-689d39da-d50a-4ced-8ae1-de6dfddff905.png)

**Comment by adrWasTaken** [comment]
If you turn off high contrast mode and run this command, does it work?

`document.body.setAttribute('style','color:var(--ic-brand-font-color-dark) !important;')`

**Comment by Jelly2011** [comment]
Yes, running that command does fix the 2nd area in both the high contrast on and off. That command does not fix the 1st area in high contrast mode

**Comment by TyHil** [comment]
No high contrast mode here. Running that command also fixes the 2nd area but not the 1st area for me.
