### ISSUE TITLE
Causes Absurd CPU Utilization

### ISSUE THREAD

**Issue by FieldPickle** [canvasplus/extension#51]
Causing any loaded Canvas page to use 30-65+ % of CPU.

After loading noticed that my computer was chugging and investigated to find that chrome>canvas page was responsible. Confirmed was extension related by disabling and re-enabling one by one and narrowed down to Canvas plus. :( 

Have attempted to relaunch chrome to no avail.

![Windows Task manager screenshot](https://user-images.githubusercontent.com/104335335/188293052-ae18bab2-8328-43e9-8831-ee1109d6a687.jpg)
![Google task manager screenshot](https://user-images.githubusercontent.com/104335335/188293053-2ecee127-8304-4035-b775-2f643a48926a.jpg)

My Specs and Details:
- CPU:   Intel i7-10750H (running @4.2GHz)
- RAM:  16GB 2933 Mhz 
- GPU1: Integrated
- GPU2: 2070 max-Q

**Edit**
-Also Tried to toggle individual settings of the extension and I observed no difference.

Here is the debug info:

(0.4.4) kdkadcnebmokaadholinmnpjelphnghh // Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 // Installation Info: {"from":"install","timestamp":1650851862179} Survey Seed (1): 0.48828869456892465

**Comment by adriancasares** [comment]
I'm sorry to hear about this! I will look into this as soon as possible and keep you updated.

**Comment by adriancasares** [comment]
Can you please show me your chrome task manager with and without canvas+ enabled? Thank you.

**Comment by FieldPickle** [comment]
![image](https://user-images.githubusercontent.com/104335335/188794091-39b0b7c2-3e6e-47c0-956b-99939d3aa848.png)
No Canvas Plus

Cant seem to replicate the issue with the current Configuration i have running. I'm not using my IGPU like i was then, i'm strictly running on the nvidia 2070 maxq and will post again if the behavior returns when i'm back in IGP mode.
